name: learn github actions

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: run dependencies
        run: npm install

      - name: run tests
        run: npm test
